

# server 설정
server:
  port:8000


zuul:
  routes:
    member:
      path: /member/**
      url : http://localhost:8081/user
    timeLine:
      path: /time/**
      url : http://localhost:8082/time
    commetn:
      path: /comment/**
      url : http://localhost:8082/comment


ribbon:
  eureka:
    enabled: false

