
# server 설정
server:
  port : 8000


zuul:
  routes:
    member:
      path: /member/**
      serviceId: member
      stripPrefix: false
    timeLine:
      path: /time/**
      serviceId: timeLine
      stripPrefix: false
    comment:
      path: /comment/**
      serviceId : timeLine
      stripPrefix : false
  ignored-services: '*'


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


